#!/usr/bin/env python

from pymetweather.pymetweather import run_app
from pymetweather.get_args import get_command_line_args, get_config_args

if __name__ == "__main__":
    args = get_config_args()
    args.update(get_command_line_args())
    run_app(args)
